jjwt:
  secret: 984hg493gh0439rthr0429uruj2309yh937gc763fe87t3f89723gf222984hg493gh0439rthr0429uruj2309yh937gc763fe87t3f89723gf222
  access: 30m
  refresh: 2592000000

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mysecuritydb
    username: postgres
    password: Vl020282
    driver-class-name: org.postgresql.Driver
  jpa:
#    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update

      #      ddl-auto: create //если такая настройка база данных будет создаваться заново (пустая) при перезапуске проекта
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: public
#  sql:
#    init:
#      mode: always
upload:
  path: D:\Program\Java\Spring\mySecurityProject\src\main\resources